### ISSUE TITLE
Television control cards

### ISSUE THREAD

**Issue by acesyde** [lovelace-rounded/ui#10]
> **_NOTE:_** Depends on https://github.com/lovelace-rounded/ui/issues/7

## Preview

![Image](https://user-images.githubusercontent.com/958435/225561259-8f100d78-bd28-4b11-9da2-49da96d4574e.png)

## Description

Reuse generic button card
* Check if the TV can use each actions (if the entity doesn't support an action, you can greyed it)

## Todo

* translations
* editor
* card
* documentation

## Button card code

```yaml
type: custom:button-card
icon: mdi:home-variant
aspect_ratio: 1/1
entity: media_player.sony_bravia_tv
show_name: false
tap_action:
  action: call-service
  haptic: medium
  service: remote.send_command
  service_data:
    entity_id: remote.sony_bravia_tv
    command: Home
styles:
  card:
    - border-radius: 24px
    - background-color: var(--contrast2)
  icon:
    - width: 32px
    - color: var(--contrast8)
state:
  - value: 'on'
    styles:
      icon:
        - color: var(--contrast20)
```
