### ISSUE TITLE
Vacuum maintenance cards

### ISSUE THREAD

**Issue by acesyde** [lovelace-rounded/ui#13]
## Preview

![Image](https://user-images.githubusercontent.com/958435/225563197-413d71cf-3ddd-4573-a439-f58a576f77d9.png)

## Description

These four cards display the hours remaining before we need to clean specific sensors or brushes of the robot vacuum. Pressing a card triggers a pop-up that asks us to confirm whether we want to reset the hours.

> I think we can create a reusable card 

## Todo

* translations
* editor
* card
* documentation

## Button card code

```yaml
type: custom:button-card
name: >-
  [[[return
  Math.round(states["sensor.roborock_vacuum_s5e_main_brush_left"].state / 60 /
  60)]]]
styles:
  grid:
    - grid-template-areas: '"n eenheid" "l l"'
    - grid-template-columns: min-content min-content
  name:
    - font-size: 32px
    - color: var(--contrast20)
  card:
    - height: 80px
    - border-radius: 24px
    - padding: 30px 0 6px 16px
    - box-sizing: border-box
    - background: var(--contrast2)
    - box-shadow: none
  label:
    - justify-self: start
    - font-size: 12px
    - color: var(--contrast20)
    - margin-top: '-2px'
  custom_fields:
    eenheid:
      - font-size: 12px
      - color: var(--contrast9)
      - margin-bottom: 6px
      - padding-left: 2px
label: Hoofdborstel
custom_fields:
  eenheid: '&nbsp;uur'
show_label: true
tap_action:
  action: call-service
  haptic: medium
  service: script.robotstofzuiger_uren_resetten_hoofdborstel
confirmation:
  text: Onderhouds uren van de hoofdborstel resetten?
```
