### ISSUE TITLE
More info card

### ISSUE THREAD

**Issue by acesyde** [lovelace-rounded/ui#2]
Implement more info card

![Image](https://user-images.githubusercontent.com/958435/225555622-c78a6020-b0d2-4978-9c28-c27613028976.png)

* Translations
* Editor

```yaml
type: custom:button-card
name: Meer info
entity: vacuum.roborock_s5_max
show_icon: false
styles:
  card:
    - background: none
    - border-radius: 24px
    - color: var(--contrast20)
    - margin-top: 8px
    - padding: 18px 0px
    - font-size: 16px
    - border: 2px solid var(--contrast5)
tap_action:
  action: more-info
  haptic: medium
```
