### ISSUE TITLE
Title card

### ISSUE THREAD

**Issue by acesyde** [lovelace-rounded/ui#3]
![Image](https://user-images.githubusercontent.com/958435/225557467-8a675c88-2957-494f-a790-af30e76ff693.png)

* Template title
* Translations
* Editor

```yaml
type: custom:button-card
name: Title here
styles:
  card:
    - font-family: In case of a custom font, otherwise you can remove this line
    - background: none
    - padding: 16px 0
    - '--mdc-ripple-press-opacity': 0
  name:
    - font-size: 32px
    - color: var(--contrast20)
```
