### ISSUE TITLE
Scene buttons

### ISSUE THREAD

**Issue by acesyde** [lovelace-rounded/ui#7]
## Preview

![Image](https://user-images.githubusercontent.com/958435/225559212-0aeb9ca6-b5b2-4bbc-bf01-6a7481b2967b.png)

## Description

Create a generic button card with entity / action holder / icon_color / background_color
This button can be hosted in vertical / horizontal card or grid card

## Todo

* translations
* editor
* card
* documentation

## Button card code

```yaml
columns: 4
type: grid
cards:
  - type: custom:button-card
    icon: mdi:sofa-single
    aspect_ratio: 1/1
    tap_action:
      action: call-service
      service: scene.turn_on
      haptic: medium
      service_data:
        entity_id: scene.gezellig
    styles:
      card:
        - border-radius: 24px
        - background-color: var(--blue)
      icon:
        - color: var(--black)
  - type: etc.. (copy the custom button-card above to add more)
```
